openapi: "3.0.0"
info:
  version: 1.0.0
  title: Go Algorithm
  description: Sets of algorithms implemented in Go
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  /algorithm/binary-search:
    $ref: "algorithmBinarySearch.yaml"
